# Generated by Django 5.0.3 on 2024-05-19 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoKids_Integracao', '0002_usuario_total_pontuacao_usuariotarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
