# Generated by Django 5.0.3 on 2024-04-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoKids_Integracao', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
