# Generated by Django 4.2.7 on 2024-04-21 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcoKids_Integracao', '0004_mural'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mural',
            new_name='Forum',
        ),
    ]
